services:
  - type: web
    name: autocare-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && chmod +x startup.sh && python manage.py collectstatic --noinput"
    startCommand: "./startup.sh"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: WEB_CONCURRENCY
        value: 2
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
