# Generated by Django 6.0.6 on 2026-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('last_value', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('prefix', 'year')},
            },
        ),
    ]
