# Generated by Django 6.0.6 on 2026-06-25 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brake_check', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=15)),
                ('engine_check', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=15)),
                ('oil_leakage_check', models.CharField(choices=[('no_issue', 'No Issue'), ('issue_found', 'Issue Found'), ('na', 'N/A')], max_length=15)),
                ('ac_check', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=15)),
                ('tyre_check', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=15)),
                ('test_drive', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('na', 'N/A')], max_length=15)),
                ('overall_status', models.CharField(choices=[('approved', 'Approved'), ('rework_required', 'Rework Required')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to=settings.AUTH_USER_MODEL)),
                ('service_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='service_jobs.servicejob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
